//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunshineRentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fleet
    {
        public Fleet()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int FleetId { get; set; }
        public string LicencePlate { get; set; }
        public int TypeId { get; set; }
        public int Kilometrage { get; set; }
        public string Image { get; set; }
        public bool ReadyToUse { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
