//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunshineRentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalId { get; set; }
        public int FleetId { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartRentalDate { get; set; }
        public System.DateTime EndRentalDate { get; set; }
        public Nullable<System.DateTime> ActualEndRental { get; set; }
    
        public virtual Fleet Fleet { get; set; }
    }
}
