//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunshineRentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Fleets = new HashSet<Fleet>();
        }
    
        public int TypeId { get; set; }
        public int ManufactorId { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public bool Transmission { get; set; }
        public decimal DailyRentalRate { get; set; }
        public decimal PenaltyDailyRate { get; set; }
    
        public virtual ICollection<Fleet> Fleets { get; set; }
        public virtual Manufactor Manufactor { get; set; }
    }
}
